package config

type ChainConfig struct {
	ChainId string `json:"chainId"`
	Name    string `json:"name"`
}

var SUPPORTED_CHAINS = []ChainConfig{
	{ChainId: "1", Name: "Ethereum Mainnet"},
	{ChainId: "56", Name: "BNB Smart Chain Mainnet"},
	{ChainId: "42161", Name: "Arbitrum One"},
	{ChainId: "8453", Name: "Base"},
	{ChainId: "43114", Name: "Avalanche C-Chain"},
	{ChainId: "59144", Name: "Linea"},
	{ChainId: "137", Name: "Polygon Mainnet"},
	{ChainId: "10", Name: "OP Mainnet"},
	{ChainId: "5", Name: "Goerli"},
	{ChainId: "100", Name: "Gnosis"},
	{ChainId: "169", Name: "Manta Pacific Mainnet"},
	{ChainId: "223", Name: "B2 Mainnet"},
	{ChainId: "252", Name: "Fraxtal"},
	{ChainId: "324", Name: "zkSync Mainnet"},
	{ChainId: "1992", Name: "Hubble Exchange"},
	{ChainId: "4200", Name: "Merlin Mainnet"},
	{ChainId: "5000", Name: "Mantle"},
	{ChainId: "7700", Name: "Canto"},
	{ChainId: "34443", Name: "Mode"},
	{ChainId: "42220", Name: "Celo Mainnet"},
	{ChainId: "42793", Name: "Etherlink Mainnet"},
	{ChainId: "48900", Name: "Zircuit Mainnet"},
	{ChainId: "60808", Name: "Bob"},
	{ChainId: "80084", Name: "Berachain bArtio"},
	{ChainId: "81457", Name: "Blast"},
	{ChainId: "111188", Name: "re.al"},
	{ChainId: "534352", Name: "Scroll"},
	{ChainId: "11155111", Name: "Sepolia"},
	{ChainId: "1329", Name: "Sei Network"},
	{ChainId: "810180", Name: "zkLink Nova Mainnet"},
	{ChainId: "7560", Name: "Cyber Mainnet"},
	{ChainId: "6001", Name: "Bounce Bit"},
	{ChainId: "2222", Name: "Kava"},
	{ChainId: "12306", Name: "Fibonacci Mainnet"},
	{ChainId: "955305", Name: "Eluvio Content Fabric"},
	{ChainId: "14", Name: "Flare Mainnet"},
	{ChainId: "813", Name: "Qitmeer Network Mainnet"},
	{ChainId: "1089", Name: "Humans.ai Mainnet"},
	{ChainId: "19", Name: "Songbird Canary-Network"},
	{ChainId: "79", Name: "Zenith Mainnet"},
	{ChainId: "1284", Name: "Moonbeam"},
	{ChainId: "1285", Name: "Moonriver"},
	{ChainId: "55", Name: "Zyx Mainnet"},
	{ChainId: "721", Name: "Lycan Chain"},
	{ChainId: "818", Name: "BeOne Chain Mainnet"},
	{ChainId: "1666600000", Name: "Harmony Mainnet Shard 0"},
	{ChainId: "50", Name: "XDC Network"},
	{ChainId: "61", Name: "Ethereum Classic"},
	{ChainId: "75", Name: "Decimal Smart Chain Mainnet"},
	{ChainId: "288", Name: "Boba Network"},
	{ChainId: "314", Name: "Filecoin - Mainnet"},
	{ChainId: "463", Name: "Areon Network Mainnet"},
	{ChainId: "2021", Name: "Edgeware EdgeEVM Mainnet"},
	{ChainId: "7000", Name: "ZetaChain Mainnet"},
	{ChainId: "8881", Name: "Quartz by Unique"},
	{ChainId: "10024", Name: "Gon Chain"},
	{ChainId: "622277", Name: "Hypra Mainnet"},
	{ChainId: "20181205", Name: "quarkblockchain"},
	{ChainId: "46", Name: "Darwinia Network"},
	{ChainId: "57", Name: "Syscoin Mainnet"},
	{ChainId: "58", Name: "Ontology Mainnet"},
	{ChainId: "113", Name: "Dehvo"},
	{ChainId: "121", Name: "Realchain Mainnet"},
	{ChainId: "204", Name: "opBNB Mainnet"},
	{ChainId: "713", Name: "Vrcscan Mainnet"},
	{ChainId: "1319", Name: "AIA Mainnet"},
	{ChainId: "2031", Name: "Centrifuge"},
	{ChainId: "2332", Name: "SOMA Network Mainnet"},
	{ChainId: "3338", Name: "peaq"},
	{ChainId: "4999", Name: "BlackFort Exchange Network"},
	{ChainId: "8880", Name: "Unique"},
	{ChainId: "8883", Name: "Sapphire by Unique"},
	{ChainId: "9996", Name: "Mind Smart Chain Mainnet"},
	{ChainId: "10000", Name: "Smart Bitcoin Cash"},
	{ChainId: "18159", Name: "Proof Of Memes"},
	{ChainId: "18888", Name: "Titan (TKX)"},
	{ChainId: "32520", Name: "Bitgert Mainnet"},
	{ChainId: "56288", Name: "Boba BNB Mainnet"},
	{ChainId: "78281", Name: "Dragonfly Mainnet (Hexapod)"},
	{ChainId: "200901", Name: "Bitlayer Mainnet"},
	{ChainId: "20201022", Name: "Pego Network"},
	{ChainId: "25", Name: "Cronos Mainnet"},
	{ChainId: "81", Name: "Japan Open Chain Mainnet"},
	{ChainId: "87", Name: "Nova Network"},
	{ChainId: "108", Name: "ThunderCore Mainnet"},
	{ChainId: "185", Name: "Mint Mainnet"},
	{ChainId: "242", Name: "Plinga Mainnet"},
	{ChainId: "250", Name: "Fantom Opera"},
	{ChainId: "254", Name: "Swan Chain Mainnet"},
	{ChainId: "274", Name: "LaChain"},
	{ChainId: "321", Name: "KCC Mainnet"},
	{ChainId: "336", Name: "Shiden"},
	{ChainId: "369", Name: "PulseChain"},
	{ChainId: "480", Name: "World Chain"},
	{ChainId: "520", Name: "XT Smart Chain Mainnet"},
	{ChainId: "786", Name: "MAAL Chain"},
	{ChainId: "868", Name: "Fantasia Chain Mainnet"},
	{ChainId: "1116", Name: "Core Blockchain Mainnet"},
	{ChainId: "1818", Name: "Cube Chain Mainnet"},
	{ChainId: "2000", Name: "Dogechain Mainnet"},
	{ChainId: "2049", Name: "Movo Smart Chain Mainnet"},
	{ChainId: "3797", Name: "AlveyChain Mainnet"},
	{ChainId: "4242", Name: "Nexi Mainnet"},
	{ChainId: "5165", Name: "Bahamut"},
	{ChainId: "5424", Name: "edeXa Mainnet"},
	{ChainId: "6999", Name: "PolySmartChain"},
	{ChainId: "7778", Name: "Orenium Mainnet Protocol"},
	{ChainId: "7862", Name: "MaalChain V2"},
	{ChainId: "8898", Name: "Mammoth Mainnet"},
	{ChainId: "10101", Name: "Blockchain Genesis Mainnet"},
	{ChainId: "10201", Name: "MaxxChain Mainnet"},
	{ChainId: "10946", Name: "Quadrans Blockchain"},
	{ChainId: "11235", Name: "Haqq Network"},
	{ChainId: "26483", Name: "DucatusX"},
	{ChainId: "26863", Name: "OasisChain Mainnet"},
	{ChainId: "61916", Name: "DoKEN Super Chain Mainnet"},
	{ChainId: "71111", Name: "GuapcoinX"},
	{ChainId: "88888", Name: "Chiliz Chain Mainnet"},
}
