package config

type ChainConfig struct {
	ChainId string `json:"chainId"`
	Name    string `json:"name"`
}

var SUPPORTED_CHAINS = []ChainConfig{
	// $$START$$
	{ChainId: "1", Name: "Ethereum Mainnet"},
	{ChainId: "56", Name: "BNB Smart Chain Mainnet"},
	{ChainId: "42161", Name: "Arbitrum One"},
	{ChainId: "8453", Name: "Base"},
	{ChainId: "43114", Name: "Avalanche C-Chain"},
	{ChainId: "59144", Name: "Linea"},
	{ChainId: "137", Name: "Polygon Mainnet"},
	{ChainId: "10", Name: "OP Mainnet"},
	{ChainId: "5", Name: "Goerli"},
	{ChainId: "100", Name: "Gnosis"},
	{ChainId: "169", Name: "Manta Pacific Mainnet"},
	{ChainId: "223", Name: "B2 Mainnet"},
	{ChainId: "252", Name: "Fraxtal"},
	{ChainId: "324", Name: "zkSync Mainnet"},
	{ChainId: "1992", Name: "Hubble Exchange"},
	{ChainId: "4200", Name: "Merlin Mainnet"},
	{ChainId: "5000", Name: "Mantle"},
	{ChainId: "7700", Name: "Canto"},
	{ChainId: "34443", Name: "Mode"},
	{ChainId: "42220", Name: "Celo Mainnet"},
	{ChainId: "42793", Name: "Etherlink Mainnet"},
	{ChainId: "48900", Name: "Zircuit Mainnet"},
	{ChainId: "60808", Name: "Bob"},
	{ChainId: "80084", Name: "Berachain bArtio"},
	{ChainId: "81457", Name: "Blast"},
	{ChainId: "111188", Name: "re.al"},
	{ChainId: "534352", Name: "Scroll"},
	{ChainId: "11155111", Name: "Sepolia"},
	{ChainId: "1329", Name: "Sei Network"},
	{ChainId: "810180", Name: "zkLink Nova Mainnet"},
	{ChainId: "7560", Name: "Cyber Mainnet"},
	{ChainId: "6001", Name: "Bounce Bit"},
	{ChainId: "2222", Name: "Kava"},
	{ChainId: "1284", Name: "Moonbeam"},
	{ChainId: "1285", Name: "Moonriver"},
	{ChainId: "61", Name: "Ethereum Classic"},
	{ChainId: "288", Name: "Boba Network"},
	{ChainId: "314", Name: "Filecoin - Mainnet"},
	{ChainId: "463", Name: "Areon Network Mainnet"},
	{ChainId: "2021", Name: "Edgeware EdgeEVM Mainnet"},
	{ChainId: "7000", Name: "ZetaChain Mainnet"},
	{ChainId: "58", Name: "Ontology Mainnet"},
	{ChainId: "204", Name: "opBNB Mainnet"},
	{ChainId: "32520", Name: "Bitgert Mainnet"},
	{ChainId: "56288", Name: "Boba BNB Mainnet"},
	{ChainId: "200901", Name: "Bitlayer Mainnet"},
	{ChainId: "25", Name: "Cronos Mainnet"},
	{ChainId: "480", Name: "World Chain"},
	{ChainId: "88888", Name: "Chiliz Chain Mainnet"},
	{ChainId: "30", Name: "Rootstock"},
	{ChainId: "2649", Name: "AILayer"},
	{ChainId: "167000", Name: "Taiko"},
	{ChainId: "2020", Name: "Ronin"},
	{ChainId: "250", Name: "Fantom"},
	{ChainId: "8217", Name: "Kaia"},
	{ChainId: "1088", Name: "Metis"},
	{ChainId: "40", Name: "Telos"},
	{ChainId: "388", Name: "Cronos zkEVM"},
	{ChainId: "8822", Name: "IOTA EVM"},
	{ChainId: "747", Name: "Flow"},
	{ChainId: "1729", Name: "Reya Network"},
	{ChainId: "2410", Name: "K2"},
	{ChainId: "592", Name: "Astar"},
	{ChainId: "4689", Name: "IoTeX"},
	{ChainId: "1313161554", Name: "Aurora"},
	{ChainId: "33139", Name: "ApeChain"},
	{ChainId: "13371", Name: "Immutable zkEVM"},
	{ChainId: "1101", Name: "Polygon zkEVM"},
	{ChainId: "71402", Name: "GodwokenV1"},
	{ChainId: "432204", Name: "Dexalot"},
	{ChainId: "3776", Name: "Astar zkEVM"},
	// $$END$$
}
